import { useMemo, useState } from "react";
import { useApp, mutate, audit, notify, logComm, uid, todayISO, fmtDate, fmtDateShort, fmtMoney, classOf, feeTotal, paidBy, monthKeys, monthLabel, type Payment } from "../lib/data";
import { Ic } from "../components/icons";
import { Modal, Confirm, Field, Chip, Avatar, Pagination, toast, PrintPortal, DuoBars, HBars, AreaChart, printNow } from "../components/ui";
import { photoFor } from "../lib/media";
import { PageHead } from "./Dashboard";

function ReceiptDoc({ p }: { p: Payment }) {
  const s = useApp();
  const db = s.db;
  const st = db.students.find((x) => x.id === p.studentId);
  const c = st ? classOf(db, st) : undefined;
  const bal = st ? Math.max(0, feeTotal(db, c?.level ?? 1) - paidBy(db, st.id)) : 0;
  return (
    <div className="print-card mx-auto max-w-[620px] bg-white text-ink-900 border border-ink-200 rounded-lg overflow-hidden">
      <div className="bg-ink-950 text-white px-6 py-4 flex items-center justify-between">
        <div>
          <div className="font-display font-bold text-[18px]">{db.school.name}</div>
          <div className="text-[10.5px] text-ink-300">{db.school.address} · {db.school.phone}</div>
        </div>
        <div className="text-right">
          <div className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-gold-400">Official receipt</div>
          <div className="font-mono font-bold text-[15px]">{p.receipt}</div>
        </div>
      </div>
      <div className="px-6 py-5">
        <div className="grid grid-cols-2 gap-4 text-[13px]">
          <div><div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">Student</div><b>{st?.first} {st?.last}</b><div className="text-[11.5px] text-ink-400">{st?.regNo} · {c?.name} {c?.section}</div></div>
          <div><div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">Parent / guardian</div><b>{st?.parent.name}</b><div className="text-[11.5px] text-ink-400">{st?.parent.phone}</div></div>
          <div><div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">Date</div><b>{fmtDate(p.date)}</b></div>
          <div><div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">Payment method</div><b>{p.method}</b></div>
        </div>
        <div className="mt-5 rounded-xl bg-ink-50 border border-ink-100 p-4 flex items-center justify-between">
          <div>
            <div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">Amount received — {p.feeType}</div>
            <div className="font-display font-bold text-[26px] tnum">{fmtMoney(p.amount, db.school.currency)}</div>
          </div>
          <div className="text-right">
            <div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">Remaining balance</div>
            <div className={`font-display font-bold text-[18px] tnum ${bal > 0 ? "text-rose-600" : "text-emerald-600"}`}>{fmtMoney(bal, db.school.currency)}</div>
          </div>
        </div>
        <div className="flex items-end justify-between mt-8">
          <div className="text-[10px] text-ink-400">Generated by VITECH School Management System<br />Verify: {db.school.website}/verify · {p.receipt}</div>
          <div className="w-40 border-t border-ink-400 pt-1 text-center text-[10px] font-bold uppercase tracking-wider text-ink-500">Cashier signature</div>
        </div>
      </div>
    </div>
  );
}

export function FeesPage() {
  const s = useApp();
  const db = s.db;
  const cur = db.school.currency;
  const [editLvl, setEditLvl] = useState<number | null>(null);
  const fs = editLvl !== null ? db.feeStructures.find((f) => f.level === editLvl) : undefined;
  return (
    <div>
      <PageHead title="Fees & Structures" sub={`Fee schedules per level — ${db.feeStructures.length} structures for ${db.school.academicYear}`} />
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {db.feeStructures.map((f) => {
          const total = f.items.reduce((a, b) => a + b.amount, 0);
          const enrolled = db.students.filter((x) => x.status === "active" && classOf(db, x)?.level === f.level).length;
          return (
            <div key={f.level} className="panel p-5 hover:shadow-lift hover:-translate-y-0.5 transition-all">
              <div className="flex items-start justify-between">
                <span className="w-11 h-11 rounded-xl bg-ink-950 dark:bg-cobalt-600 text-gold-400 flex items-center justify-center font-display font-bold">S{f.level}</span>
                <button className="btn-g btn-sm" onClick={() => setEditLvl(f.level)}><Ic n="pencil" size={14} />Edit</button>
              </div>
              <h3 className="font-display font-bold text-[17px] mt-3">Senior {f.level}</h3>
              <p className="text-[12px] text-ink-400 font-semibold">{enrolled} enrolled students</p>
              <div className="mt-3 space-y-1.5">
                {f.items.map((it) => (
                  <div key={it.id} className="flex justify-between text-[13px]"><span className="text-ink-500 dark:text-ink-300">{it.name}</span><b className="tnum">{fmtMoney(it.amount, cur)}</b></div>
                ))}
                <div className="flex justify-between text-[13.5px] pt-2 border-t border-ink-100 dark:border-ink-800"><b>Total / year</b><b className="tnum text-cobalt-700 dark:text-cobalt-300">{fmtMoney(total, cur)}</b></div>
              </div>
            </div>
          );
        })}
      </div>
      {fs && (
        <Modal open onClose={() => setEditLvl(null)} title={`Fee structure — Senior ${fs.level}`} w="max-w-md"
          footer={<><button className="btn-o" onClick={() => setEditLvl(null)}>Cancel</button><button className="btn-p" onClick={() => { audit("UPDATE_FEES", "Fees", `Senior ${fs.level} structure updated`); toast("Fee structure saved"); setEditLvl(null); }}><Ic n="check" size={15} />Save</button></>}>
          <div className="space-y-3">
            {fs.items.map((it) => (
              <div key={it.id} className="flex items-center gap-3">
                <span className="text-[13px] font-bold flex-1">{it.name}</span>
                <input type="number" className="input !w-36 tnum" value={it.amount} onChange={(e) => mutate((db) => { const x = db.feeStructures.find((f) => f.level === fs.level)!.items.find((y) => y.id === it.id)!; x.amount = +e.target.value; })} />
              </div>
            ))}
            <div className="flex justify-between font-bold text-[14px] pt-2 border-t border-ink-100 dark:border-ink-800"><span>Total</span><span className="tnum">{fmtMoney(fs.items.reduce((a, b) => a + b.amount, 0), cur)}</span></div>
          </div>
        </Modal>
      )}
    </div>
  );
}

export function PaymentsPage() {
  const s = useApp();
  const db = s.db;
  const cur = db.school.currency;
  const [q, setQ] = useState("");
  const [page, setPage] = useState(1);
  const [form, setForm] = useState(false);
  const [receipt, setReceipt] = useState<Payment | null>(null);
  const [f, setF] = useState({ studentId: db.students[0]?.id ?? "", amount: 50000, method: "Mobile Money", feeType: "Tuition" });
  const filtered = useMemo(() => [...db.payments].sort((a, b) => b.date.localeCompare(a.date)).filter((p) => {
    const st = db.students.find((x) => x.id === p.studentId);
    return !q || `${p.receipt} ${st?.first} ${st?.last} ${st?.regNo}`.toLowerCase().includes(q.toLowerCase());
  }), [db.payments, db.students, q]);
  const per = 10;
  const pages = Math.max(1, Math.ceil(filtered.length / per));
  const shown = filtered.slice((page - 1) * per, page * per);
  const todayTotal = db.payments.filter((p) => p.date === todayISO()).reduce((a, b) => a + b.amount, 0);

  const record = () => {
    const st = db.students.find((x) => x.id === f.studentId);
    if (!st || f.amount <= 0) { toast("Select a student and a valid amount", "err"); return; }
    const receiptNo = `${db.school.receiptPrefix}-${todayISO().slice(2).replace(/-/g, "")}${String(db.payments.length + 1).padStart(3, "0")}`;
    const p: Payment = { id: uid(), receipt: receiptNo, studentId: st.id, amount: f.amount, method: f.method, feeType: f.feeType, date: todayISO() };
    mutate((db) => db.payments.unshift(p));
    const bal = Math.max(0, feeTotal(db, classOf(db, st)?.level ?? 1) - paidBy(db, st.id));
    logComm("SMS", st.parent.phone || "+250 7XX", `Payment of ${fmtMoney(f.amount, cur)} received for ${st.first} ${st.last}. Remaining balance: ${fmtMoney(bal, cur)}. — ${db.school.name}`);
    audit("RECORD_PAYMENT", "Payments", `${receiptNo} · ${fmtMoney(f.amount, cur)} · ${st.first} ${st.last}`);
    notify("payment", "Payment received", `${receiptNo} — ${fmtMoney(f.amount, cur)} (${st.first} ${st.last})`);
    toast(`Payment recorded — receipt ${receiptNo}`);
    setForm(false); setReceipt(p);
  };
  const exportCSV = () => {
    const rows = filtered.map((p) => { const st = db.students.find((x) => x.id === p.studentId); return [p.receipt, `${st?.first} ${st?.last}`, p.method, p.feeType, p.date, p.amount].join(","); });
    const blob = new Blob([["Receipt,Student,Method,FeeType,Date,Amount", ...rows].join("\n")], { type: "text/csv" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "payments.csv"; a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 3000);
    audit("EXPORT_PAYMENTS", "Payments", `Exported ${filtered.length} payments`);
    toast("Payments exported to CSV");
  };
  return (
    <div>
      <PageHead title="Payments" sub={`${db.payments.length} payments · ${fmtMoney(todayTotal, cur)} collected today`}>
        <button className="btn-o btn-sm" onClick={exportCSV}><Ic n="download" size={15} />Export</button>
        <button className="btn-p btn-sm" onClick={() => setForm(true)}><Ic n="plus" size={15} />Record payment</button>
      </PageHead>
      <div className="panel overflow-hidden">
        <div className="p-4 border-b border-ink-100 dark:border-ink-800">
          <div className="relative max-w-sm"><Ic n="search" size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-300" /><input className="input !pl-9" placeholder="Search receipt or student…" value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} /></div>
        </div>
        <div className="overflow-x-auto">
          <table className="tbl">
            <thead><tr><th>Receipt</th><th>Student</th><th>Method</th><th>Fee type</th><th className="hidden sm:table-cell">Date</th><th className="!text-right">Amount</th><th></th></tr></thead>
            <tbody>
              {shown.map((p) => {
                const st = db.students.find((x) => x.id === p.studentId);
                return (
                  <tr key={p.id}>
                    <td className="font-mono text-[12px] font-bold text-cobalt-600 dark:text-cobalt-300 whitespace-nowrap">{p.receipt}</td>
                    <td><span className="flex items-center gap-2.5">{st && <Avatar first={st.first} last={st.last} hue={st.hue} size={28} photo={photoFor(st.id)} />}<span><span className="block font-bold text-[13px] whitespace-nowrap">{st?.first} {st?.last}</span><span className="block text-[11px] text-ink-400">{st?.regNo}</span></span></span></td>
                    <td><Chip tone={p.method === "Mobile Money" ? "gold" : p.method === "Cash" ? "green" : "blue"}>{p.method}</Chip></td>
                    <td className="text-[12.5px] text-ink-500 dark:text-ink-300">{p.feeType}</td>
                    <td className="hidden sm:table-cell text-[12.5px] text-ink-400 whitespace-nowrap">{fmtDateShort(p.date)}</td>
                    <td className="text-right font-bold tnum whitespace-nowrap">{fmtMoney(p.amount, cur)}</td>
                    <td className="text-right"><button className="btn-g btn-sm !px-2" title="View receipt" onClick={() => setReceipt(p)}><Ic n="printer" size={15} /></button></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <Pagination page={page} pages={pages} onPage={setPage} total={filtered.length} shown={shown.length} />
      </div>
      <Modal open={form} onClose={() => setForm(false)} title="Record payment" w="max-w-md"
        footer={<><button className="btn-o" onClick={() => setForm(false)}>Cancel</button><button className="btn-p" onClick={record}><Ic n="check" size={15} />Record & issue receipt</button></>}>
        <div className="space-y-4">
          <Field label="Student"><select className="input" value={f.studentId} onChange={(e) => setF({ ...f, studentId: e.target.value })}>{db.students.filter((x) => x.status === "active").slice(0, 120).map((x) => <option key={x.id} value={x.id}>{x.first} {x.last} — {x.regNo}</option>)}</select></Field>
          <div className="grid grid-cols-2 gap-4">
            <Field label={`Amount (${cur})`}><input type="number" className="input tnum" value={f.amount} onChange={(e) => setF({ ...f, amount: +e.target.value })} /></Field>
            <Field label="Fee type"><select className="input" value={f.feeType} onChange={(e) => setF({ ...f, feeType: e.target.value })}>{["Tuition", "Registration", "Examination", "Transport", "Library", "Other"].map((x) => <option key={x}>{x}</option>)}</select></Field>
          </div>
          <Field label="Method"><select className="input" value={f.method} onChange={(e) => setF({ ...f, method: e.target.value })}>{["Mobile Money", "Cash", "Bank", "Card", "Transfer"].map((x) => <option key={x}>{x}</option>)}</select></Field>
        </div>
      </Modal>
      {receipt && (
        <Modal open onClose={() => setReceipt(null)} title={`Receipt ${receipt.receipt}`} w="max-w-2xl"
          footer={<><button className="btn-o" onClick={() => setReceipt(null)}>Close</button><button className="btn-p" onClick={() => printNow(<ReceiptDoc p={receipt} />)}><Ic n="printer" size={15} />Print / PDF</button></>}>
          <ReceiptDoc p={receipt} />
        </Modal>
      )}
    </div>
  );
}

export function InvoicesPage() {
  const s = useApp();
  const db = s.db;
  const cur = db.school.currency;
  const rows = db.students.filter((x) => x.status === "active").map((x) => {
    const total = feeTotal(db, classOf(db, x)?.level ?? 1);
    return { x, total, paid: paidBy(db, x.id), bal: total - paidBy(db, x.id) };
  }).sort((a, b) => b.bal - a.bal);
  const unpaid = rows.filter((r) => r.bal > 0);
  const remind = (name: string, bal: number, phone: string) => {
    logComm("SMS", phone || "+250 7XX", `Fee reminder — ${name}: ${fmtMoney(bal, cur)} outstanding. — ${db.school.name}`);
    audit("SEND_REMINDER", "Invoices", `Fee reminder to ${name}`);
    toast("Reminder sent via SMS");
  };
  return (
    <div>
      <PageHead title="Invoices" sub={`${unpaid.length} students with outstanding balances`}>
        <button className="btn-o btn-sm" onClick={() => { unpaid.slice(0, 20).forEach((r) => logComm("SMS", r.x.parent.phone || "+250 7XX", `Fee reminder — ${r.x.first} ${r.x.last}: ${fmtMoney(r.bal, cur)} outstanding. — ${db.school.name}`)); audit("SEND_REMINDERS", "Invoices", `Bulk reminders to ${Math.min(20, unpaid.length)} parents`); toast("Bulk reminders queued via SMS"); }}><Ic n="sms" size={15} />Remind all unpaid</button>
      </PageHead>
      <div className="panel overflow-hidden">
        <div className="overflow-x-auto">
          <table className="tbl">
            <thead><tr><th>Student</th><th>Annual fees</th><th>Paid</th><th>Balance</th><th>Status</th><th className="!text-right">Action</th></tr></thead>
            <tbody>
              {rows.slice(0, 30).map((r) => (
                <tr key={r.x.id}>
                  <td><span className="flex items-center gap-2.5"><Avatar first={r.x.first} last={r.x.last} hue={r.x.hue} size={28} photo={photoFor(r.x.id)} /><span><b className="block text-[13px] whitespace-nowrap">{r.x.first} {r.x.last}</b><span className="block text-[11px] text-ink-400">{classOf(db, r.x)?.name} {classOf(db, r.x)?.section}</span></span></span></td>
                  <td className="tnum font-semibold whitespace-nowrap">{fmtMoney(r.total, cur)}</td>
                  <td className="tnum text-emerald-600 whitespace-nowrap">{fmtMoney(r.paid, cur)}</td>
                  <td className={`tnum font-bold whitespace-nowrap ${r.bal > 0 ? "text-rose-500" : "text-emerald-600"}`}>{fmtMoney(Math.max(0, r.bal), cur)}</td>
                  <td><Chip tone={r.bal <= 0 ? "green" : r.paid > 0 ? "amber" : "red"}>{r.bal <= 0 ? "Paid" : r.paid > 0 ? "Partial" : "Unpaid"}</Chip></td>
                  <td className="text-right">{r.bal > 0 && <button className="btn-g btn-sm" onClick={() => remind(`${r.x.first} ${r.x.last}`, r.bal, r.x.parent.phone)}><Ic n="sms" size={14} />Remind</button>}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export function ExpensesPage() {
  const s = useApp();
  const db = s.db;
  const cur = db.school.currency;
  const [form, setForm] = useState(false);
  const [del, setDel] = useState<string | null>(null);
  const [f, setF] = useState({ category: "Supplies", desc: "", amount: 10000, vendor: "", method: "Cash" });
  const add = () => {
    if (!f.desc || f.amount <= 0) { toast("Description and amount are required", "err"); return; }
    mutate((db) => db.expenses.unshift({ id: uid(), ...f, date: todayISO(), by: "Jean Bosco" }));
    audit("CREATE_EXPENSE", "Expenses", `${f.category} · ${fmtMoney(f.amount, cur)} · ${f.vendor}`);
    toast("Expense recorded"); setForm(false); setF({ category: "Supplies", desc: "", amount: 10000, vendor: "", method: "Cash" });
  };
  const total = db.expenses.reduce((a, b) => a + b.amount, 0);
  return (
    <div>
      <PageHead title="Expenses" sub={`${db.expenses.length} expenses · ${fmtMoney(total, cur)} total`}>
        <button className="btn-p btn-sm" onClick={() => setForm(true)}><Ic n="plus" size={15} />New expense</button>
      </PageHead>
      <div className="panel overflow-hidden">
        <div className="overflow-x-auto">
          <table className="tbl">
            <thead><tr><th>Category</th><th>Description</th><th>Vendor</th><th className="hidden sm:table-cell">Date</th><th className="!text-right">Amount</th><th></th></tr></thead>
            <tbody>
              {db.expenses.slice(0, 25).map((e) => (
                <tr key={e.id}>
                  <td><Chip tone={e.category === "Salaries" ? "navy" : "gray"}>{e.category}</Chip></td>
                  <td className="text-[13px] max-w-[280px] truncate">{e.desc}</td>
                  <td className="text-[12.5px] text-ink-400 whitespace-nowrap">{e.vendor}</td>
                  <td className="hidden sm:table-cell text-[12.5px] text-ink-400 whitespace-nowrap">{fmtDateShort(e.date)}</td>
                  <td className="text-right font-bold tnum whitespace-nowrap text-rose-500">−{fmtMoney(e.amount, cur)}</td>
                  <td className="text-right"><button className="btn-g btn-sm !px-2 !text-rose-500" onClick={() => setDel(e.id)} aria-label="Delete"><Ic n="trash" size={14} /></button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <Modal open={form} onClose={() => setForm(false)} title="New expense" w="max-w-md"
        footer={<><button className="btn-o" onClick={() => setForm(false)}>Cancel</button><button className="btn-p" onClick={add}><Ic n="check" size={15} />Record</button></>}>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <Field label="Category"><select className="input" value={f.category} onChange={(e) => setF({ ...f, category: e.target.value })}>{["Salaries", "Electricity", "Internet", "Rent", "Maintenance", "Supplies", "Transport", "Equipment", "Other"].map((x) => <option key={x}>{x}</option>)}</select></Field>
            <Field label={`Amount (${cur})`}><input type="number" className="input tnum" value={f.amount} onChange={(e) => setF({ ...f, amount: +e.target.value })} /></Field>
          </div>
          <Field label="Description"><input className="input" value={f.desc} onChange={(e) => setF({ ...f, desc: e.target.value })} /></Field>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Vendor"><input className="input" value={f.vendor} onChange={(e) => setF({ ...f, vendor: e.target.value })} /></Field>
            <Field label="Method"><select className="input" value={f.method} onChange={(e) => setF({ ...f, method: e.target.value })}>{["Cash", "Bank", "Mobile Money"].map((x) => <option key={x}>{x}</option>)}</select></Field>
          </div>
        </div>
      </Modal>
      <Confirm open={!!del} onClose={() => setDel(null)} title="Delete expense?" body="This removes the expense record permanently."
        onYes={() => { if (del) { mutate((db) => { db.expenses = db.expenses.filter((x) => x.id !== del); }); audit("DELETE_EXPENSE", "Expenses", "Expense removed"); toast("Expense deleted", "info"); } }} />
    </div>
  );
}

export function FinReportsPage() {
  const s = useApp();
  const db = s.db;
  const cur = db.school.currency;
  const mk = monthKeys(8);
  const revBy = mk.map((m) => db.payments.filter((p) => p.date.startsWith(m)).reduce((a, b) => a + b.amount, 0));
  const expBy = mk.map((m) => db.expenses.filter((p) => p.date.startsWith(m)).reduce((a, b) => a + b.amount, 0));
  const byMethod = ["Mobile Money", "Cash", "Bank", "Card", "Transfer"].map((m) => ({ label: m, value: db.payments.filter((p) => p.method === m).reduce((a, b) => a + b.amount, 0) })).filter((x) => x.value > 0);
  const byClass = db.classes.map((c) => ({ label: `${c.name} ${c.section}`, value: Math.round(db.students.filter((x) => x.classId === c.id).reduce((a, x) => a + Math.min(paidBy(db, x.id), feeTotal(db, c.level)), 0) / 1000) })).sort((a, b) => b.value - a.value).slice(0, 6);
  const byFeeType = ["Tuition", "Registration", "Examination", "Transport", "Other"].map((t) => ({ label: t, value: db.payments.filter((p) => p.feeType === t).reduce((a, b) => a + b.amount, 0) })).filter((x) => x.value > 0);
  const exportCSV = (name: string, rows: { label: string; value: number }[]) => {
    const blob = new Blob([["Label,Value", ...rows.map((r) => `${r.label},${r.value}`)].join("\n")], { type: "text/csv" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = name; a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 3000);
    audit("EXPORT_REPORT", "Finance", name);
    toast(`${name} exported`);
  };
  const totalRev = revBy.reduce((a, b) => a + b, 0);
  const totalExp = expBy.reduce((a, b) => a + b, 0);
  return (
    <div>
      <PageHead title="Financial Reports" sub={`Revenue ${fmtMoney(totalRev, cur)} · Expenses ${fmtMoney(totalExp, cur)} · Net ${fmtMoney(totalRev - totalExp, cur)}`}>
        <button className="btn-o btn-sm" onClick={() => exportCSV("revenue_by_month.csv", mk.map((m, i) => ({ label: m, value: revBy[i] })))}><Ic n="download" size={15} />CSV</button>
        <button className="btn-p btn-sm" onClick={() => printNow(
          <div className="p-2 max-w-[760px] mx-auto">
            <div className="flex items-end justify-between border-b-4 border-ink-950 pb-3 mb-5">
              <div><div className="font-display font-bold text-[22px]">{db.school.name}</div><div className="text-[11px] uppercase tracking-[0.18em] text-ink-500">Financial report — last 8 months</div></div>
              <div className="text-right text-[11px] text-ink-500">Generated {fmtDate(todayISO())}<br />{db.school.currency}</div>
            </div>
            <div className="grid grid-cols-3 gap-3 mb-5 text-center">
              {[["Revenue", fmtMoney(totalRev, cur)], ["Expenses", fmtMoney(totalExp, cur)], ["Net profit", fmtMoney(totalRev - totalExp, cur)]].map(([k, v]) => (
                <div key={k} className="border border-ink-200 rounded-lg py-3"><div className="font-display font-bold text-[16px]">{v}</div><div className="text-[9.5px] font-extrabold uppercase tracking-wider text-ink-400">{k}</div></div>
              ))}
            </div>
            <table className="w-full border-collapse text-[11.5px]">
              <thead><tr><th className="border border-ink-300 bg-ink-100 px-2 py-1.5 text-left">Month</th><th className="border border-ink-300 bg-ink-100 px-2 py-1.5 text-right">Revenue</th><th className="border border-ink-300 bg-ink-100 px-2 py-1.5 text-right">Expenses</th><th className="border border-ink-300 bg-ink-100 px-2 py-1.5 text-right">Net</th></tr></thead>
              <tbody>{mk.map((m, i) => <tr key={m}><td className="border border-ink-300 px-2 py-1.5">{m}</td><td className="border border-ink-300 px-2 py-1.5 text-right tnum">{revBy[i].toLocaleString()}</td><td className="border border-ink-300 px-2 py-1.5 text-right tnum">{expBy[i].toLocaleString()}</td><td className="border border-ink-300 px-2 py-1.5 text-right tnum font-bold">{(revBy[i] - expBy[i]).toLocaleString()}</td></tr>)}</tbody>
            </table>
          </div>
        )}><Ic n="printer" size={15} />Print report</button>
      </PageHead>
      <div className="grid sm:grid-cols-3 gap-3.5 mb-4">
        {[["Total revenue", fmtMoney(totalRev, cur), "coins", "green"], ["Total expenses", fmtMoney(totalExp, cur), "expenses", "red"], ["Net profit", fmtMoney(totalRev - totalExp, cur), "analytics", "navy"]].map(([l, v, ic, tone]) => (
          <div key={l as string} className="panel p-4 flex items-center gap-3.5">
            <span className={`w-10 h-10 rounded-lg text-white flex items-center justify-center ${tone === "green" ? "bg-emerald-500" : tone === "red" ? "bg-rose-500" : "bg-ink-900 dark:bg-ink-700"}`}><Ic n={ic as string} /></span>
            <div><div className="text-[11px] font-extrabold uppercase tracking-[0.1em] text-ink-400">{l}</div><div className="font-display text-[17px] font-bold tnum">{v}</div></div>
          </div>
        ))}
      </div>
      <div className="panel mb-4">
        <div className="panel-h"><h3 className="font-display font-bold text-[16px]">Revenue vs expenses</h3><Chip tone="blue">{cur}</Chip></div>
        <div className="px-5 pb-5"><DuoBars data={mk.map((m, i) => ({ label: monthLabel(m), a: Math.round(revBy[i] / 1000), b: Math.round(expBy[i] / 1000) }))} aLabel="Revenue" bLabel="Expenses" money="K" /></div>
      </div>
      <div className="grid md:grid-cols-2 gap-4 mb-4">
        <div className="panel"><div className="panel-h"><h3 className="font-display font-bold text-[16px]">Revenue trend</h3><button className="btn-g btn-sm" onClick={() => exportCSV("revenue_trend.csv", mk.map((m, i) => ({ label: m, value: revBy[i] })))}><Ic n="download" size={14} /></button></div><div className="px-5 pb-5"><AreaChart data={revBy} labels={mk.map(monthLabel)} h={110} color="#c98f1b" id="finrev" /></div></div>
        <div className="panel p-5"><div className="panel-h !px-0 !pt-0"><h3 className="font-display font-bold text-[16px]">By payment method</h3><button className="btn-g btn-sm" onClick={() => exportCSV("by_method.csv", byMethod)}><Ic n="download" size={14} /></button></div><HBars rows={byMethod} /></div>
      </div>
      <div className="grid md:grid-cols-2 gap-4">
        <div className="panel p-5"><div className="panel-h !px-0 !pt-0"><h3 className="font-display font-bold text-[16px]">Revenue by class</h3><button className="btn-g btn-sm" onClick={() => exportCSV("by_class.csv", byClass)}><Ic n="download" size={14} /></button></div><HBars rows={byClass} money="K" /></div>
        <div className="panel p-5"><div className="panel-h !px-0 !pt-0"><h3 className="font-display font-bold text-[16px]">By fee type</h3><button className="btn-g btn-sm" onClick={() => exportCSV("by_fee_type.csv", byFeeType)}><Ic n="download" size={14} /></button></div><HBars rows={byFeeType} /></div>
      </div>
    </div>
  );
}
